export const GET_POKEMON = 'GET_POKEMON'
export const SET_CURRENT = 'SET_CURRENT'
export const SET_LOADING = 'SET_LOADING'
export const STOP_LOADING = 'STOP_LOADING'
export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'